repos:
  - repo: local
    hooks:
      - id: readme-date-check
        name: README Date Check
        entry: scripts/check_readme_date.sh
        language: script
        files: README\.md$
        pass_filenames: false
